import os
import pygame

BACKGROUND = pygame.image.load(os.path.join('Assets/Background', 'background.png'))
DIRT = pygame.image.load(os.path.join('Assets/Ground', 'dirt.png'))
DIRT_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'dirt_left.png'))
DIRT_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'dirt_right.png'))
DIRT_LEFT_RIGHT_CORNER =pygame.image.load(os.path.join('Assets/Ground', 'dirt_left_right_corner.png'))
GRASS_TOP = pygame.image.load(os.path.join('Assets/Ground', 'grass_top.png'))
GRASS_TOP_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_right.png'))
GRASS_TOP_RIGHT_CORNER_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_right_corner_right.png'))
GRASS_TOP_LEVITATE = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_levitate.png'))
GRASS_TOP_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_left.png'))
GRASS_TOP_LEFT_CORNER_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_left_corner_right.png'))
GRASS_TOP_CORNER_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_corner_right.png'))
GRASS_TOP_CORNER_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'grass_top_corner_left.png'))
GRASS_SINGLE_TOP = pygame.image.load(os.path.join('Assets/Ground', 'grass_single_top.png'))
GRASS_LEVITATE_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_levitate_right.png'))
GRASS_LEVITATE_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'grass_levitate_left.png'))
GRASS_LEVITATE_CENTER = pygame.image.load(os.path.join('Assets/Ground', 'grass_levitate_center.png'))
GRASS_CORNER_RIGHT_LEVITATE = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_right_levitate.png'))
GRASS_CORNER_RIGHT_CORNER_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_right_corner_right.png'))
GRASS_CORNER_RIGHT_BOTH_CORNERS = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_right_both_corners.png'))
GRASS_CORNER_LEFT_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_right.png'))
GRASS_CORNER_LEFT_RIGHT_CORNER_RIGHT = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_right_corner_right.png'))
GRASS_CORNER_LEFT_RIGHT_CORNER_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_right_corner_left.png'))
GRASS_CORNER_LEFT_LEVITATE = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_levitate.png'))
GRASS_CORNER_LEFT_CORNER_LEFT = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_corner_left.png'))
GRASS_CORNER_LEF_BOTH_CORNER = pygame.image.load(os.path.join('Assets/Ground', 'grass_corner_left_both_corner.png'))

